[build]
  publish = "public" # Cambia "public" si tus archivos HTML están en otro directorio
  functions = "netlify/functions"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[build]
node_version = "20"
